### ISSUE TITLE
Remove use of `configure`

### ISSUE THREAD

**Issue by kevinpschaaf** [robdodson/mark-down#15]
PSA: we are going to (soon) remove the general `configure` function, which was the predecessor to `value` in `properties`, and is pretty much an unnecessary duplicate API at this point.  Configuring default property values should be moved to `properties: { prop: { value: ... } }`.  It also looks like a pattern emerged to bind event listener functions to instance methods in `configure`; this can just be done in `created` instead.

**Comment by robdodson** [comment]
Fixed in 1.0
