### ISSUE TITLE
Demo is broken

### ISSUE THREAD

**Issue by trevordmiller** [robdodson/mark-down#8]
The demo site does not currently work, which I would assume means that the element itself does not work because of the error that is showing in `ShadowRenderer.js` on line `601`?
![screen shot 2014-07-25 at 10 49 51 am](https://cloud.githubusercontent.com/assets/5497885/3705194/30d1cb76-141c-11e4-86c6-2e905add0596.png)

**Comment by robdodson** [comment]
Should be fixed in 1.0 release
